baseURL = "https://absorbingchaos.com"
languageCode = "en-us"
theme = "abc_whoabuddy"
title = "ABC - Absorb Chaos - Release Potential"
description = "Technology services inspired by and based on freedom, collaboration, transparency, integrity, and community."
logo = "https://absorbingchaos.com/img/ABC-Logo-150-150.png"
logo_type = "image/png"
logo_width = "150"
logo_height = "150"
logo_alt = "Logo with the letters A, B, and C that represent a shortened version of absorbing chaos."
