baseURL = "https://absorbingchaos.com"
languageCode = "en-us"
theme = "abc-whoabuddy"

[params]
  company = "Absorbing Chaos"
  title = "ABC - Absorb Chaos - Release Potential"
  description = "Technology services inspired by and based on freedom, collaboration, transparency, integrity, and community."
  logo_img = "ABC-Logo-150-150.png"
  logo_type = "image/png"
  logo_width = "150"
  logo_height = "150"
  logo_alt = "Logo with the letters A, B, and C that represent a shortened version of Absorbing Chaos."

[params.palette]
  primary = "#273554"
  primary_light = "#525E81"
  primary_dark = "#000F2B"
  secondary = "#312855"
  secondary_light = "#5C5082"
  secondary_dark = "#0C002C"
  text = "#FFFFFF"
  text_light = "#D0E1F9"
  text_dark = "#273554"
