# Site settings
baseurl = "https://absorbingchaos.com"
languageCode = "en-us"
theme = "sawmill"
title = "ABC - Absorb Chaos - Release Potential"

[Author]
    name = "Jason Schrader"
[Params]
    logo = "logo.svg"
[Params.BrandColor]
    normal = "#273554"
    light = "#525e81"
    dark = "#000f2b"
    shadow = "#0c002c"
